"""Add neues_feld to product

Revision ID: c4b4726d6e8a
Revises: 37961ae1533a
Create Date: 2025-07-06 06:43:02.472922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b4726d6e8a'
down_revision: Union[str, Sequence[str], None] = '37961ae1533a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('neues_feld', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'neues_feld')
    # ### end Alembic commands ###
